### ISSUE TITLE
Cannot find UnitedMet_env.yaml file in the downloaded UnitedMet package 

### ISSUE THREAD

**Issue by yanc0828** [reznik-lab/UnitedMet#1]
When I tried to create the environment from the UnitedMet_env.yaml using the following code: 
```
source anaconda3/bin/activate
conda env create -f $HOME/UnitedMet/UnitedMet_env.yaml
```
it always shows the error:
```
EnvironmentFileNotFound: '$HOME/UnitedMet/UnitedMet_env.yaml' file not found
```
I also couldn't find the UnitedMet_env.yaml in the downloaded UnitedMet folder

Hope someone could help!

**Comment by amyyyxie** [comment]
Thanks for bring up this issue! UnitedMet_env.yml has been added.
