### ISSUE TITLE
Get errors when running imputation

### ISSUE THREAD

**Issue by yanc0828** [reznik-lab/UnitedMet#2]
After installing, I tried to run the following code with rna_matched_data_dir containing the 4 paired RNA-seq reference datasets and met_matched_data_dir containing the 4 paired metabolomics reference datasets

```
python3 -m UnitedMet.impute_met.local.UnitedMet_impute_met \
--verbose_embeddings \
--n_steps 4000 \
--learning_rate 0.001 \
-fp ${file_path} \
-rna ${rna_matched_data_dir} \
-met ${met_matched_data_dir} \
-id ${rna_imputation_data_dir} \
-ck \
-rd ${results_dir} \
-n ${ndims}
```

The first error message got is:
<img width="934" alt="Error1" src="https://github.com/reznik-lab/UnitedMet/assets/143852554/b800062c-2f6c-4ec8-9eaa-3eca986c65e8">

Modifying the data_processing.py line 131 into the following works
```
impution_dirlist = os.listdir(rna_imputation_data_dir)
impution_dirlist.sort()
dirlist = impution_dirlist + dirlist  
```

The second error message got is:
<img width="934" alt="Error2" src="https://github.com/reznik-lab/UnitedMet/assets/143852554/f842ad39-3345-47de-bcfb-b5ecf13a3bb8">

Not sure if changing the function name of check_match would solve it. 

Hope someone could help.

**Comment by amyyyxie** [comment]
Thanks for bring the issues to our attention! We've updated the UnitedMet_impute_met.py to resolve this two issues. For your second error: Yes, change the function name to anything else other than check_match will solve the problem! We updated the function name to check_match_ccRCC().
